# Generated by Django 4.0.4 on 2022-05-08 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id_folders', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('master_pwd', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=255)),
                ('id_folders', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.folders')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
