# Generated by Django 4.0.4 on 2022-05-27 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_id_user_folders_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='id_folders',
            new_name='folder',
        ),
    ]
