# Generated by Django 4.0.4 on 2022-05-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_alter_folders_id_user_alter_items_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('master_pwd', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='folders',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='items',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
