# Generated by Django 4.0.4 on 2022-05-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_id_folders_items_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='password',
            field=models.BinaryField(),
        ),
    ]
