# Generated by Django 4.0.4 on 2022-05-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_items_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
